### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by asasmith** [SilveradoPolicy/silverado#69]
https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/#gatsby-plugin-google-analytics

Need to get analytics code from Emily

**Comment by asasmith** [comment]
Waiting on config recommendations from Michelle and the GA tracking code.

**Comment by asasmith** [comment]
```js
options: {
  trackingId: // tracking id
  head: true,
  respectDNT: true,
}
```

**Comment by kcbreuil** [comment]
@asasmith I think we got this no? Do you want me to handle?
